version: '3.8'
services:
  app:
    container_name: app
    build: .
    environment:
    - SKIP_ENV_VALIDATION_E=
    - DATABASE_URL_E=postgresql://root:admin@db:5432/rewardsdb?connect_timeout=300
    - NEXTAUTH_URL_E=
    - NEXTAUTH_SECRET_E=
    - DISCORD_CLIENT_ID=
    - DISCORD_CLIENT_SECRET=
    - DISCORD_SERVER_ID_E=
    - DISCORD_BOT_TOKEN_E=
    - DISCORD_WEBHOOK_URL_E=
    command:  bash -c "sleep 20 && pnpm install && pnpm db:push & npm run dev"
    ports:
      - 5553:5553
      - 3000:3000
    networks:
      - rewards
    depends_on:
      - db
      - pgadmin
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: rewardsdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rewards
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - rewards
    restart: unless-stopped
    depends_on:
      - db

networks:
  rewards:
    driver: bridge
  